[[redirects]]
  from = "https://xn--gugbckerei-t5a.ch/*"
  to = "https://gugbaeckerei.ch/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.xn--gugbckerei-t5a.ch/*"
  to = "https://www.gugbaeckerei.ch/:splat"
  status = 301
  force = true
