seo:
  site_name: gug Bäckerei Schwyz
  title: Glutenfreie Bäckerei Schwyz – gug Bäckerei
  description: Glutenfreie Bäckerei in Schwyz. Frisches Brot, feine Patisserie, Torten und Zmittag – genussvoll, hochwertig und ohne Kompromisse.
  keywords: glutenfreie Bäckerei Schwyz, glutenfrei Brot Schwyz, glutenfreie Torten Schweiz, glutenfreie Patisserie, glutenfrei kaufen Schwyz, vegane Bäckerei Schwyz
  social_image: /images/reto-2.jpg
  author: gug Bäckerei | Reto Bommer
  favicon_image: /icons/SVG/gug-baeckerei-hauptlogo-weiss.svg
social:
  instagram_url: https://www.instagram.com/gugbaeckerei/
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#303E72'
  medium-text_color: '#D07427'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#303E72'
  medium_color: '#D07427'
  light_color: '#819941'
  v-light_color: '#FFFCF4'
  featured_color: '#51381B'
  accent_color: '#a74a4a'
neuigkeiten-banner: true
neuigkeiten-banner-text: 'Bilder zeigen noch das CaféLaden - neue folgen bald.'