seo:
  site_name: Example
  title: Example SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_url: https://www.instagram.com/gugbaeckerei/
  facebook_url:
  pinterest_url:
  linkedin_url:
design:
  dark-text_color: '#303E72'
  medium-text_color: '#D07427'
  light-text_color: '#f7f5f3'
  featured-text_color: '#ff0000'
  dark_color: '#303E72'
  medium_color: '#D07427'
  light_color: '#819941'
  v-light_color: '#FFFCF4'
  featured_color: '#51381B'
  accent_color: '#a74a4a'
neuigkeiten-banner: true
neuigkeiten-banner-text: 'Bilder zeigen noch das CaféLaden - neue folgen bald.'